<div class="space-y-7">
    <x-ui.page-header
        title="Audit Logs"
        eyebrow="Administration"
        description="Review traceable system actions generated by legacy migration and protected administrative operations."
    />

    <x-ui.card :padding="false">
        <div class="border-b border-slate-100 px-5 py-5 sm:px-6">
            <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                <div><h2 class="text-sm font-bold text-slate-900">System Audit Trail</h2><p class="mt-1 text-xs text-slate-500">Audit records are append-only from the application interface.</p></div>
                <div class="grid gap-3 sm:grid-cols-2 sm:w-[560px]">
                    <input type="search" wire:model.live.debounce.300ms="search" placeholder="Search action, user, or description..." class="rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-[#1e5a8a] focus:ring-4 focus:ring-blue-100">
                    <select wire:model.live="category" class="rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-[#1e5a8a] focus:ring-4 focus:ring-blue-100"><option value="all">All categories</option>@foreach($categories as $item)<option value="{{ $item }}">{{ ucfirst($item) }}</option>@endforeach</select>
                </div>
            </div>
        </div>

        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-slate-200">
                <thead class="bg-slate-50"><tr>
                    <th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500 sm:px-6">Date / User</th>
                    <th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Category / Action</th>
                    <th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Description</th>
                    <th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Record</th>
                    <th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500 sm:px-6">Origin</th>
                </tr></thead>
                <tbody class="divide-y divide-slate-100 bg-white">
                    @forelse($logs as $log)
                        <tr class="align-top">
                            <td class="whitespace-nowrap px-5 py-4 text-xs text-slate-600 sm:px-6"><p class="font-semibold text-slate-800">{{ $log->created_at?->format('M d, Y h:i A') ?? '—' }}</p><p class="mt-1 text-[11px] text-slate-400">{{ $log->user?->name ?? 'System' }}</p></td>
                            <td class="whitespace-nowrap px-5 py-4"><x-ui.badge variant="info">{{ ucfirst($log->category) }}</x-ui.badge><p class="mt-2 text-xs font-semibold text-slate-700">{{ str_replace('_', ' ', ucfirst($log->action)) }}</p></td>
                            <td class="min-w-[360px] px-5 py-4 text-xs leading-5 text-slate-600">{{ $log->description }}</td>
                            <td class="min-w-[220px] px-5 py-4 text-[11px] text-slate-500"><p>{{ $log->auditable_type ? class_basename($log->auditable_type) : '—' }}</p><p class="mt-1 font-mono">{{ $log->auditable_id ? '#'.$log->auditable_id : '—' }}</p></td>
                            <td class="min-w-[180px] px-5 py-4 text-[11px] text-slate-500 sm:px-6"><p>{{ $log->ip_address ?? '—' }}</p><p class="mt-1 max-w-[240px] truncate" title="{{ $log->user_agent }}">{{ $log->user_agent ?? 'Console/System' }}</p></td>
                        </tr>
                    @empty
                        <tr><td colspan="5" class="px-5 py-12 text-center text-sm text-slate-500 sm:px-6">No audit records match the selected filters.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        @if($logs->hasPages())<div class="border-t border-slate-100 px-5 py-4 sm:px-6">{{ $logs->links() }}</div>@endif
    </x-ui.card>
</div>
