<div class="space-y-6">
    @if (session()->has('monitoring-status'))
        <x-ui.alert variant="success" title="Monitoring & Compliance">{{ session('monitoring-status') }}</x-ui.alert>
    @endif

    @error('processing')
        <x-ui.alert variant="danger" title="Monitoring Locked">{{ $message }}</x-ui.alert>
    @enderror

    <x-projects.identity-card :project="$project" />

    @unless ($isUnlocked)
        <x-ui.alert variant="warning" title="Monitoring is read-only until approval">
            Monitoring, findings, follow-ups, and compliance records can be updated only after the project workflow is approved and completed.
        </x-ui.alert>
    @endunless

    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
        <x-ui.card><p class="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Accomplishment</p><p class="mt-3 text-2xl font-bold text-[#164b73]">{{ number_format($summary['accomplishment_percentage']) }}%</p><p class="mt-1 text-xs text-slate-500">Current implementation snapshot</p></x-ui.card>
        <x-ui.card><p class="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Monitoring Visits</p><p class="mt-3 text-2xl font-bold text-slate-950">{{ number_format($summary['visits_total']) }}</p><p class="mt-1 text-xs text-slate-500">Recorded project visits</p></x-ui.card>
        <x-ui.card><p class="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Open Findings</p><p class="mt-3 text-2xl font-bold text-amber-700">{{ number_format($summary['open_findings']) }}</p><p class="mt-1 text-xs text-slate-500">{{ number_format($summary['overdue_findings']) }} overdue</p></x-ui.card>
        <x-ui.card><p class="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Compliance Reports</p><p class="mt-3 text-2xl font-bold text-slate-950">{{ number_format($summary['compliance_total']) }}</p><p class="mt-1 text-xs text-slate-500">{{ number_format($summary['compliance_verified']) }} verified</p></x-ui.card>
        <x-ui.card><p class="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Overdue Reports</p><p class="mt-3 text-2xl font-bold text-red-700">{{ number_format($summary['compliance_overdue']) }}</p><p class="mt-1 text-xs text-slate-500">Reporting periods requiring action</p></x-ui.card>
    </div>

    <x-ui.card :padding="false">
        <div class="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6">
            <div><h3 class="text-sm font-bold text-slate-900">Monitoring Visits</h3><p class="mt-1 text-xs text-slate-500">Field/desk monitoring with accomplishment snapshot and next monitoring schedule.</p></div>
            @can('project-monitoring.update') @if($isUnlocked)<x-ui.button wire:click="startVisit">Add Monitoring Visit</x-ui.button>@endif @endcan
        </div>

        @if ($showVisitForm)
            <div class="border-b border-slate-100 bg-slate-50/60 px-5 py-5 sm:px-6">
                <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                    <div><label class="block text-xs font-semibold text-slate-600">Visit Type</label><select wire:model="visit_type" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach($visitTypes as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</select>@error('visit_type')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                    <div><label class="block text-xs font-semibold text-slate-600">Visit Date</label><input type="date" wire:model="visit_date" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">@error('visit_date')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                    <div><label class="block text-xs font-semibold text-slate-600">Status</label><select wire:model="visit_status" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach($visitStatuses as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</select></div>
                    <div><label class="block text-xs font-semibold text-slate-600">Accomplishment %</label><input type="number" min="0" max="100" wire:model="visit_accomplishment" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">@error('visit_accomplishment')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                    <div><label class="block text-xs font-semibold text-slate-600">Conducted By</label><input type="text" wire:model="conducted_by_name" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></div>
                    <div><label class="block text-xs font-semibold text-slate-600">Location</label><input type="text" wire:model="visit_location" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></div>
                    <div><label class="block text-xs font-semibold text-slate-600">Next Monitoring Date</label><input type="date" wire:model="next_monitoring_date" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">@error('next_monitoring_date')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                    <div class="md:col-span-2"><label class="block text-xs font-semibold text-slate-600">Observations</label><textarea rows="3" wire:model="observations" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></textarea></div>
                    <div class="md:col-span-2"><label class="block text-xs font-semibold text-slate-600">Recommendations</label><textarea rows="3" wire:model="recommendations" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></textarea></div>
                </div>
                <div class="mt-4 flex justify-end gap-2"><x-ui.button variant="secondary" wire:click="cancelVisit">Cancel</x-ui.button><x-ui.button wire:click="saveVisit">Save Visit</x-ui.button></div>
            </div>
        @endif

        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr>
            <th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500 sm:px-6">Visit</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Status</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Accomplishment</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Observations / Next</th><th class="px-5 py-3 text-right text-[10px] font-bold uppercase tracking-wide text-slate-500 sm:px-6">Action</th>
        </tr></thead><tbody class="divide-y divide-slate-100 bg-white">
            @forelse($project->monitoringVisits->sortByDesc('visit_date') as $visit)<tr class="align-top">
                <td class="min-w-[220px] px-5 py-4 sm:px-6"><p class="text-xs font-bold text-slate-900">{{ $visit->visit_type->label() }}</p><p class="mt-1 text-xs text-slate-500">{{ $visit->visit_date->format('M d, Y') }}</p><p class="mt-1 text-[11px] text-slate-400">{{ $visit->conducted_by_name ?: 'No monitor specified' }}</p></td>
                <td class="px-5 py-4"><x-ui.badge :variant="$visit->status->badgeVariant()">{{ $visit->status->label() }}</x-ui.badge></td>
                <td class="px-5 py-4"><p class="text-sm font-bold text-[#164b73]">{{ $visit->accomplishment_percentage }}%</p><p class="mt-1 text-[11px] text-slate-400">{{ $visit->findings->count() }} finding(s)</p></td>
                <td class="min-w-[300px] px-5 py-4 text-xs leading-5 text-slate-600"><p>{{ $visit->observations ?: '—' }}</p>@if($visit->next_monitoring_date)<p class="mt-2 font-semibold text-slate-700">Next: {{ $visit->next_monitoring_date->format('M d, Y') }}</p>@endif</td>
                <td class="whitespace-nowrap px-5 py-4 text-right sm:px-6">@can('project-monitoring.update') @if($isUnlocked)<button wire:click="editVisit({{ $visit->id }})" class="text-xs font-bold text-[#164b73]">Edit</button><button wire:click="startFinding({{ $visit->id }})" class="ml-3 text-xs font-bold text-[#164b73]">Add Finding</button>@endif @endcan</td>
            </tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-sm text-slate-500">No monitoring visits recorded.</td></tr>@endforelse
        </tbody></table></div>
    </x-ui.card>

    <x-ui.card :padding="false">
        <div class="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><h3 class="text-sm font-bold text-slate-900">Findings & Corrective Actions</h3><p class="mt-1 text-xs text-slate-500">Track issues through due dates, resolution, and follow-up history.</p></div>@can('project-monitoring.update') @if($isUnlocked)<x-ui.button wire:click="startFinding">Add Finding</x-ui.button>@endif @endcan</div>
        @if($showFindingForm)
            <div class="border-b border-slate-100 bg-slate-50/60 px-5 py-5 sm:px-6"><div class="grid gap-4 md:grid-cols-2">
                <div><label class="block text-xs font-semibold text-slate-600">Related Visit</label><select wire:model="finding_visit_id" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">No specific visit</option>@foreach($project->monitoringVisits->sortByDesc('visit_date') as $visit)<option value="{{ $visit->id }}">{{ $visit->visit_date->format('M d, Y') }} · {{ $visit->visit_type->label() }}</option>@endforeach</select></div>
                <div><label class="block text-xs font-semibold text-slate-600">Status</label><select wire:model="finding_status" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach($findingStatuses as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</select></div>
                <div class="md:col-span-2"><label class="block text-xs font-semibold text-slate-600">Finding</label><textarea rows="3" wire:model="finding_text" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></textarea>@error('finding_text')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="block text-xs font-semibold text-slate-600">Corrective Action</label><textarea rows="3" wire:model="corrective_action" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></textarea></div>
                <div><label class="block text-xs font-semibold text-slate-600">Due Date</label><input type="date" wire:model="finding_due_date" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></div>
                <div class="md:col-span-2"><label class="block text-xs font-semibold text-slate-600">Resolution Notes</label><textarea rows="2" wire:model="resolution_notes" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></textarea>@error('resolution_notes')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            </div><div class="mt-4 flex justify-end gap-2"><x-ui.button variant="secondary" wire:click="cancelFinding">Cancel</x-ui.button><x-ui.button wire:click="saveFinding">Save Finding</x-ui.button></div></div>
        @endif

        @if($showFollowUpForm)
            <div class="border-b border-blue-100 bg-blue-50/60 px-5 py-5 sm:px-6"><p class="text-xs font-bold uppercase tracking-wide text-[#164b73]">Record Finding Follow-up</p><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                <div><label class="block text-xs font-semibold text-slate-600">Follow-up Date</label><input type="date" wire:model="follow_up_date" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></div>
                <div><label class="block text-xs font-semibold text-slate-600">Status After Follow-up</label><select wire:model="follow_up_status" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach($findingStatuses as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</select></div>
                <div><label class="block text-xs font-semibold text-slate-600">Next Follow-up</label><input type="date" wire:model="next_follow_up_date" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></div>
                <div class="md:col-span-2 xl:col-span-4"><label class="block text-xs font-semibold text-slate-600">Follow-up Notes</label><textarea rows="3" wire:model="follow_up_notes" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></textarea>@error('follow_up_notes')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            </div><div class="mt-4 flex justify-end gap-2"><x-ui.button variant="secondary" wire:click="cancelFollowUp">Cancel</x-ui.button><x-ui.button wire:click="saveFollowUp">Save Follow-up</x-ui.button></div></div>
        @endif

        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500 sm:px-6">Finding</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Status / Due</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Corrective Action</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Follow-ups</th><th class="px-5 py-3 text-right text-[10px] font-bold uppercase tracking-wide text-slate-500 sm:px-6">Action</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">
            @forelse($project->monitoringFindings->sortByDesc('id') as $finding)<tr class="align-top"><td class="min-w-[300px] px-5 py-4 text-xs leading-5 text-slate-700 sm:px-6"><p class="font-semibold">{{ $finding->finding }}</p>@if($finding->visit)<p class="mt-1 text-[11px] text-slate-400">Visit: {{ $finding->visit->visit_date->format('M d, Y') }}</p>@endif</td><td class="whitespace-nowrap px-5 py-4"><x-ui.badge :variant="$finding->isOverdue() ? 'danger' : $finding->status->badgeVariant()">{{ $finding->isOverdue() ? 'Overdue' : $finding->status->label() }}</x-ui.badge><p class="mt-2 text-[11px] text-slate-500">Due {{ $finding->due_date?->format('M d, Y') ?? '—' }}</p></td><td class="min-w-[260px] px-5 py-4 text-xs leading-5 text-slate-600">{{ $finding->corrective_action ?: '—' }}@if($finding->resolution_notes)<p class="mt-2 border-t border-slate-100 pt-2 text-emerald-700">{{ $finding->resolution_notes }}</p>@endif</td><td class="px-5 py-4 text-xs text-slate-600"><span class="font-bold">{{ $finding->followUps->count() }}</span><span class="text-slate-400"> recorded</span>@if($finding->followUps->first())<p class="mt-1 text-[11px] text-slate-400">Latest {{ $finding->followUps->first()->follow_up_date->format('M d, Y') }}</p>@endif</td><td class="whitespace-nowrap px-5 py-4 text-right sm:px-6">@can('project-monitoring.update') @if($isUnlocked)<button wire:click="editFinding({{ $finding->id }})" class="text-xs font-bold text-[#164b73]">Edit</button><button wire:click="startFollowUp({{ $finding->id }})" class="ml-3 text-xs font-bold text-[#164b73]">Follow-up</button>@endif @endcan</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-sm text-slate-500">No monitoring findings recorded.</td></tr>@endforelse
        </tbody></table></div>
    </x-ui.card>

    <x-ui.card :padding="false">
        <div class="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><h3 class="text-sm font-bold text-slate-900">Reporting & Compliance Periods</h3><p class="mt-1 text-xs text-slate-500">Track report periods, due dates, submission/verification status, accomplishment, and linked documentary evidence.</p></div>@can('project-monitoring.update') @if($isUnlocked)<x-ui.button wire:click="startCompliance">Add Reporting Period</x-ui.button>@endif @endcan</div>
        @if($showComplianceForm)
            <div class="border-b border-slate-100 bg-slate-50/60 px-5 py-5 sm:px-6"><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                <div><label class="block text-xs font-semibold text-slate-600">Report Type</label><input type="text" wire:model="report_type" placeholder="e.g. Quarterly Progress Report" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">@error('report_type')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="block text-xs font-semibold text-slate-600">Period Label</label><input type="text" wire:model="period_label" placeholder="e.g. Q1 2026" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></div>
                <div><label class="block text-xs font-semibold text-slate-600">Period Start</label><input type="date" wire:model="period_start" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></div>
                <div><label class="block text-xs font-semibold text-slate-600">Period End</label><input type="date" wire:model="period_end" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></div>
                <div><label class="block text-xs font-semibold text-slate-600">Due Date</label><input type="date" wire:model="compliance_due_date" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></div>
                <div><label class="block text-xs font-semibold text-slate-600">Status</label><select wire:model="compliance_status" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach($complianceStatuses as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</select></div>
                <div><label class="block text-xs font-semibold text-slate-600">Accomplishment %</label><input type="number" min="0" max="100" wire:model="compliance_accomplishment" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></div>
                <div><label class="block text-xs font-semibold text-slate-600">Linked Document</label><select wire:model="linked_document_id" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">No linked document</option>@foreach($project->documents as $document)<option value="{{ $document->id }}">{{ $document->name }}</option>@endforeach</select></div>
                <div class="md:col-span-2 xl:col-span-4"><label class="block text-xs font-semibold text-slate-600">Remarks</label><textarea rows="3" wire:model="compliance_remarks" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></textarea></div>
            </div><div class="mt-4 flex justify-end gap-2"><x-ui.button variant="secondary" wire:click="cancelCompliance">Cancel</x-ui.button><x-ui.button wire:click="saveCompliance">Save Reporting Period</x-ui.button></div></div>
        @endif
        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500 sm:px-6">Report / Period</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Due / Status</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Accomplishment</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">Evidence</th><th class="px-5 py-3 text-right text-[10px] font-bold uppercase tracking-wide text-slate-500 sm:px-6">Action</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">
            @forelse($project->complianceReports->sortByDesc('due_date') as $report)<tr class="align-top"><td class="min-w-[250px] px-5 py-4 sm:px-6"><p class="text-xs font-bold text-slate-900">{{ $report->report_type }}</p><p class="mt-1 text-xs text-slate-500">{{ $report->period_label ?: collect([$report->period_start?->format('M d, Y'), $report->period_end?->format('M d, Y')])->filter()->implode(' – ') ?: 'No period specified' }}</p></td><td class="whitespace-nowrap px-5 py-4"><x-ui.badge :variant="$report->isOverdue() ? 'danger' : $report->status->badgeVariant()">{{ $report->isOverdue() ? 'Overdue' : $report->status->label() }}</x-ui.badge><p class="mt-2 text-[11px] text-slate-500">Due {{ $report->due_date?->format('M d, Y') ?? '—' }}</p></td><td class="px-5 py-4 text-sm font-bold text-[#164b73]">{{ $report->accomplishment_percentage !== null ? $report->accomplishment_percentage.'%' : '—' }}</td><td class="min-w-[220px] px-5 py-4 text-xs text-slate-600">@if($report->document)<a href="{{ route('projects.documents.download', [$project, $report->document]) }}" class="font-semibold text-[#164b73]">{{ $report->document->name }}</a>@else<span class="text-slate-400">No linked document</span>@endif</td><td class="whitespace-nowrap px-5 py-4 text-right sm:px-6">@can('project-monitoring.update') @if($isUnlocked)<button wire:click="editCompliance({{ $report->id }})" class="text-xs font-bold text-[#164b73]">Edit</button>@endif @endcan</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-sm text-slate-500">No reporting or compliance periods recorded.</td></tr>@endforelse
        </tbody></table></div>
    </x-ui.card>
</div>
