<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DILP {{ $report['title'] }} Report</title>
    <style>
        * { box-sizing: border-box; }
        body { margin: 0; padding: 24px; font-family: Arial, sans-serif; color: #111827; background: #fff; font-size: 10px; }
        .toolbar { display: flex; justify-content: flex-end; margin-bottom: 16px; }
        .toolbar button { border: 1px solid #cbd5e1; border-radius: 6px; background: #fff; padding: 8px 12px; font-weight: 700; cursor: pointer; }
        .agency { text-align: center; line-height: 1.5; }
        .agency .department { font-size: 12px; font-weight: 700; }
        .agency h1 { margin: 8px 0 2px; font-size: 16px; text-transform: uppercase; }
        .agency p { margin: 0; color: #475569; }
        .filters { margin: 14px 0; padding: 8px 10px; border: 1px solid #cbd5e1; background: #f8fafc; }
        .metrics { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; margin: 12px 0; }
        .metric { border: 1px solid #cbd5e1; padding: 8px; }
        .metric .label { font-size: 8px; text-transform: uppercase; color: #64748b; font-weight: 700; }
        .metric .value { margin-top: 4px; font-size: 13px; font-weight: 700; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #94a3b8; padding: 5px 6px; vertical-align: top; }
        th { background: #e2e8f0; text-align: left; font-size: 8px; text-transform: uppercase; }
        .number { text-align: right; white-space: nowrap; }
        .footer { margin-top: 12px; display: flex; justify-content: space-between; color: #64748b; font-size: 8px; }
        @page { size: landscape; margin: 10mm; }
        @media print { body { padding: 0; } .toolbar { display: none; } }
    </style>
</head>
<body>
    <div class="toolbar"><button onclick="window.print()">Print Report</button></div>

    <div class="agency">
        <div>Republic of the Philippines</div>
        <div class="department">DEPARTMENT OF LABOR AND EMPLOYMENT</div>
        <h1>DILP {{ $report['title'] }} Report</h1>
        <p>{{ $report['description'] }}</p>
    </div>

    <div class="filters">
        @foreach ($report['filterLabels'] as $label => $value)
            <strong>{{ $label }}:</strong> {{ $value }}@unless($loop->last) &nbsp; | &nbsp; @endunless
        @endforeach
    </div>

    <div class="metrics">
        @foreach ($report['summary'] as $metric)
            <div class="metric">
                <div class="label">{{ $metric['label'] }}</div>
                <div class="value">
                    @if (($metric['type'] ?? null) === 'money')
                        ₱{{ number_format((float) $metric['value'], 2) }}
                    @elseif (($metric['type'] ?? null) === 'percent')
                        {{ number_format((float) $metric['value'], 2) }}%
                    @else
                        {{ number_format((float) $metric['value']) }}
                    @endif
                </div>
            </div>
        @endforeach
    </div>

    <table>
        <thead><tr>@foreach ($report['columns'] as $column)<th>{{ $column['label'] }}</th>@endforeach</tr></thead>
        <tbody>
            @forelse ($report['rows'] as $row)
                <tr>
                    @foreach ($report['columns'] as $column)
                        @php($value = $row[$column['key']] ?? null)
                        <td class="{{ in_array($column['type'] ?? null, ['money','integer','percent'], true) ? 'number' : '' }}">
                            @if (($column['type'] ?? null) === 'money')
                                ₱{{ number_format((float) $value, 2) }}
                            @elseif (($column['type'] ?? null) === 'percent')
                                {{ number_format((float) $value, 2) }}%
                            @elseif (($column['type'] ?? null) === 'integer')
                                {{ number_format((int) $value) }}
                            @else
                                {{ $value ?? '—' }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ count($report['columns']) }}" style="text-align:center;padding:18px;">No records match the selected filters.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <span>Generated by DILP Reporting and Monitoring System</span>
        <span>{{ $report['generatedAt']->format('F d, Y h:i A') }}</span>
    </div>
</body>
</html>
