<?php

return [
    'max_file_mb' => (int) env('LEGACY_IMPORT_MAX_MB', 25),
    'max_rows' => (int) env('LEGACY_IMPORT_MAX_ROWS', 50000),
    'allowed_extensions' => ['csv', 'xlsx'],

    'fields' => [
        'fiscal_year' => 'Fiscal Year *',
        'project_code' => 'Project Code',
        'title' => 'Project Title *',
        'proponent_name' => 'Proponent Name *',
        'proponent_type' => 'Proponent Type',
        'office' => 'Office / Provincial Office',
        'fund_source' => 'Fund Source',
        'project_type' => 'Project Type *',
        'project_purpose' => 'Project Purpose *',
        'implementation_mode' => 'Implementation Mode',
        'date_received' => 'Date Received',
        'province' => 'Province',
        'municipality' => 'Municipality / City',
        'barangay' => 'Barangay',
        'address_detail' => 'Address Detail',
        'equipment_materials_tools' => 'Equipment / Materials / Tools',
        'insurance' => 'Insurance',
        'training' => 'Training',
        'proponent_partner_equity' => 'Proponent / Partner Equity',
        'beneficiary_equity' => 'Beneficiary Equity',
        'livelihood' => 'Livelihood Type',
        'target_beneficiaries' => 'Target Beneficiaries',
        'source_reference' => 'Legacy Source Reference',
        'record_status' => 'Record Status',
        'remarks' => 'Remarks',
    ],

    'required_fields' => [
        'fiscal_year', 'title', 'proponent_name', 'project_type', 'project_purpose',
    ],

    'aliases' => [
        'fiscal_year' => ['fiscal year', 'fy', 'year', 'cy', 'calendar year'],
        'project_code' => ['project code', 'project no', 'project number', 'dilp code', 'code'],
        'title' => ['project title', 'title', 'project name', 'livelihood project'],
        'proponent_name' => ['proponent', 'proponent name', 'beneficiary/proponent', 'name of proponent', 'organization'],
        'proponent_type' => ['proponent type', 'type of proponent', 'individual/group'],
        'office' => ['office', 'provincial office', 'field office', 'po', 'dole office'],
        'fund_source' => ['fund source', 'fund', 'source of fund', 'funding source'],
        'project_type' => ['project type', 'type', 'individual/group project'],
        'project_purpose' => ['project purpose', 'purpose', 'formation/enhancement'],
        'implementation_mode' => ['implementation mode', 'mode of implementation', 'mode'],
        'date_received' => ['date received', 'received date', 'date of receipt'],
        'province' => ['province', 'prov'],
        'municipality' => ['municipality', 'city/municipality', 'municipality/city', 'city', 'mun/city'],
        'barangay' => ['barangay', 'brgy', 'brgy.'],
        'address_detail' => ['address', 'address detail', 'location detail'],
        'equipment_materials_tools' => ['equipment/materials/tools', 'equipment materials tools', 'emt', 'dole assistance', 'dole share'],
        'insurance' => ['insurance', 'insurance cost'],
        'training' => ['training', 'training cost'],
        'proponent_partner_equity' => ['proponent/partner equity', 'partner equity', 'proponent equity'],
        'beneficiary_equity' => ['beneficiary equity', 'beneficiary counterpart'],
        'livelihood' => ['livelihood', 'livelihood type', 'enterprise', 'project category'],
        'target_beneficiaries' => ['target beneficiaries', 'no. of beneficiaries', 'number of beneficiaries', 'beneficiaries'],
        'source_reference' => ['source reference', 'reference', 'legacy reference', 'spreadsheet reference'],
        'record_status' => ['record status', 'status'],
        'remarks' => ['remarks', 'notes', 'comment'],
    ],
];
