<div class="space-y-7">
<x-ui.page-header title="Funds & Targets" eyebrow="Program Monitoring" description="Set annual fund allocations and project/beneficiary targets, then compare them against actual DILP records.">@can('fund-targets.update')<x-slot:actions><x-ui.button wire:click="startCreate">Add Fund Target</x-ui.button></x-slot:actions>@endcan</x-ui.page-header>
@if(session()->has('fund-status'))<x-ui.alert variant="success" title="Funds & Targets">{{ session('fund-status') }}</x-ui.alert>@endif
<div class="flex items-end gap-3"><div><label class="block text-xs font-bold text-slate-600">Fiscal Year</label><select wire:model.live="year" class="mt-2 rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-sm">@foreach($years as $item)<option value="{{ $item }}">FY {{ $item }}</option>@endforeach</select></div></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
<x-ui.card><p class="text-[10px] font-bold uppercase tracking-wide text-slate-400">Allocation</p><p class="mt-3 text-xl font-bold text-slate-950">₱{{ number_format($summary['allocation'],2) }}</p></x-ui.card>
<x-ui.card><p class="text-[10px] font-bold uppercase tracking-wide text-slate-400">Target Projects</p><p class="mt-3 text-2xl font-bold">{{ number_format($summary['target_projects']) }}</p></x-ui.card>
<x-ui.card><p class="text-[10px] font-bold uppercase tracking-wide text-slate-400">Actual Projects</p><p class="mt-3 text-2xl font-bold text-[#164b73]">{{ number_format($summary['actual_projects']) }}</p></x-ui.card>
<x-ui.card><p class="text-[10px] font-bold uppercase tracking-wide text-slate-400">Target Beneficiaries</p><p class="mt-3 text-2xl font-bold">{{ number_format($summary['target_beneficiaries']) }}</p></x-ui.card>
<x-ui.card><p class="text-[10px] font-bold uppercase tracking-wide text-slate-400">Actual Beneficiaries</p><p class="mt-3 text-2xl font-bold text-[#164b73]">{{ number_format($summary['actual_beneficiaries']) }}</p></x-ui.card>
</div>
@if($showForm)
<x-ui.card><h2 class="text-sm font-bold text-slate-900">{{ $editingId ? 'Edit Fund Target' : 'New Fund Target' }}</h2><div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
<div><label class="text-xs font-bold text-slate-600">Fiscal Year</label><input type="number" wire:model="year" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@error('year')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
<div><label class="text-xs font-bold text-slate-600">Fund Source</label><select wire:model="fund_source_id" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">Select fund source</option>@foreach($fundSources as $fund)<option value="{{ $fund->id }}">{{ $fund->name }}</option>@endforeach</select>@error('fund_source_id')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
<div><label class="text-xs font-bold text-slate-600">Office Scope</label><select wire:model="office_id" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">Regional / All Offices</option>@foreach($offices as $office)<option value="{{ $office->id }}">{{ $office->name }}</option>@endforeach</select></div>
<div><label class="text-xs font-bold text-slate-600">Allocation Amount</label><input type="number" step="0.01" wire:model="allocation_amount" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"></div>
<div><label class="text-xs font-bold text-slate-600">Target Projects</label><input type="number" wire:model="target_projects" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"></div>
<div><label class="text-xs font-bold text-slate-600">Target Beneficiaries</label><input type="number" wire:model="target_beneficiaries" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"></div>
<div class="md:col-span-2 xl:col-span-3"><label class="text-xs font-bold text-slate-600">Remarks</label><textarea wire:model="remarks" rows="3" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"></textarea></div>
</div><div class="mt-5 flex gap-2"><x-ui.button wire:click="save">Save Target</x-ui.button><x-ui.button variant="secondary" wire:click="cancel">Cancel</x-ui.button></div></x-ui.card>
@endif
<x-ui.card :padding="false"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr>
<th class="px-5 py-3 text-left text-[10px] font-bold uppercase text-slate-500">Fund / Scope</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase text-slate-500">Allocation</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase text-slate-500">Projects</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase text-slate-500">Beneficiaries</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase text-slate-500">Actual DOLE Share</th><th class="px-5 py-3 text-right text-[10px] font-bold uppercase text-slate-500">Action</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($targets as $target)<tr><td class="px-5 py-4"><p class="text-sm font-bold text-slate-900">{{ $target->fundSource?->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $target->office?->name ?? 'Regional / All Offices' }}</p></td><td class="px-5 py-4 text-xs"><p class="font-bold">₱{{ number_format((float)$target->allocation_amount,2) }}</p><p class="mt-1 text-slate-500">Balance ₱{{ number_format((float)$target->allocation_balance,2) }}</p></td><td class="px-5 py-4 text-xs"><p>{{ $target->actual_projects }} actual / {{ $target->target_projects }} target</p></td><td class="px-5 py-4 text-xs"><p>{{ $target->actual_beneficiaries }} actual / {{ $target->target_beneficiaries }} target</p></td><td class="px-5 py-4 text-xs font-bold">₱{{ number_format((float)$target->actual_dole_share,2) }}</td><td class="px-5 py-4 text-right">@can('fund-targets.update')<button wire:click="edit({{ $target->id }})" class="text-xs font-bold text-[#164b73]">Edit</button>@endcan</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-sm text-slate-500">No fund targets configured for FY {{ $year }}.</td></tr>@endforelse
</tbody></table></div></x-ui.card>
</div>
